P11
birzhans/test-guru pull request #12
Opened 2020-11-10 08:24 UTC by birzhans

2020-11-10 09:17 UTC, BubuntuClu requested changes

2020-11-10 09:17 UTC, BubuntuClu commented on app/controllers/admin/base_controller.rb
> +    redirect_to root_path, alert: 'You are not authorized to view this page.' unless current_user.is_a?(Admin)
добавь метод в модель `User` который будет проверять является ли пользователь админом. `admin?`

2020-11-10 09:17 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +  def admin_required!
это должно быть в application_controller, раз в других контрллерах ты обращаешься к этому метода и наследуешься от application, а не от answer

2020-11-10 09:17 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +  skip_before_action :authenticate_user!
почему тут идет скип проверки?

2020-11-10 09:17 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +  layout 'admin'
эти контроллеры должны быть в неймспейсе админа, их нужно передвинуть

2020-11-10 09:17 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    if current_user.is_a?(Admin)
когда добавишь метод будет resources.admin?

2020-11-10 09:17 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def admin_required!
не наводит на мысли, если ты копируешь одно и тоже в нескольких местах, то значит что-то не так ты делаешь? эти методы можно унаследовать

2020-11-10 13:44 UTC, BubuntuClu requested changes

2020-11-10 13:44 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  before_action :admin_required!
тебе проверку админа надо делать только для админских контроллеров.  для этого application_controllera не надо это делать.
надо создать папку admin, в нее перенести/создать нужные контроллеры и там уже делать эту проверку. 
старые контроллеры, которые не будут в админке, не должны аффектиться проверкой админа

2020-11-11 07:35 UTC, BubuntuClu requested changes

2020-11-11 07:35 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +class Admin::AnswersController < ApplicationController
раз это админский контроллер, его надо наследовать от  Admin::BaseController

2020-11-11 07:35 UTC, BubuntuClu commented on app/controllers/admin/answers_controller.rb
> +  layout 'admin'
это не надо, если правильно будешь наследовать

2020-11-11 07:35 UTC, BubuntuClu commented on app/controllers/admin/questions_controller.rb
> +  layout 'admin'
это тоже

2020-11-11 07:35 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +      @test.update(author_id: current_user.id)
а если не пройдет апдейт? 
так же ты делаешь тут два запроса в БД вместо одного.
у тебя есть ассоциация созданных тестов пользователем, ее надо использовать на 17ой строчке

2020-11-11 07:35 UTC, BubuntuClu commented on app/controllers/admin/tests_controller.rb
> +  def start
в админке не нужен старт

2020-11-11 07:35 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  def after_sign_in_path_for(resources)
тут надо с ресурсом работать, а не с текущим пользователем

2020-11-11 07:35 UTC, BubuntuClu commented on app/models/test.rb
> +  def author
так, у тебя куда-то пропала ассоциация "автор теста". возможно я ее проглядел.
в этом уроке https://thinknetica.teachbase.ru/course_sessions/243072/tasks/9172/view#user_id=1799335&session_id=243072 надо было сделать еще одну ассоциацию "Между Тестом и автором (Пользователем), который его создал."

тогда добавишь ее сейчас. после надо будет возможно переименовать метод(смотря как ассоциацию назовешь) и переделать чуток код

2020-11-11 18:39 UTC, birzhans commented on app/models/test.rb
> +  def author
Есть ассоциация tests_created, забыл про нее

2020-11-14 18:17 UTC, merged