P13: bootstrap
birzhans/test-guru pull request #15
Opened 2020-11-15 18:22 UTC by birzhans

2020-11-15 21:34 UTC, BubuntuClu requested changes

2020-11-15 21:34 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    if key == "alert"
а другие ключи? всегда будет успех, если пришла не ошибка?

2020-11-15 21:34 UTC, BubuntuClu commented on app/views/admin/tests/show.html.erb
> +	<%= link_to t('.new'), new_admin_test_question_path(@test), class: "btn btn-primary" %>
чет отступы поехали

2020-11-15 21:34 UTC, BubuntuClu commented on app/views/admin/tests/show.html.erb
> +	<%= link_to t('.new'), new_admin_test_question_path(@test), class: "btn btn-primary" %>
лучше заменить в ИДЕ все табы на 2(4) пробела

2020-11-16 08:37 UTC, BubuntuClu commented on app/views/shared/_header.html.erb
> +  <% if current_user.is_a?(Admin) %>
current_user.admin?

И тут не или должно быть, а если ты админ, то дополнительная ссылка на админку

2020-11-16 09:23 UTC, birzhans commented on app/views/shared/_header.html.erb
> +  <% if current_user.is_a?(Admin) %>
понял

2020-11-16 09:29 UTC, merged