P18: badges
birzhans/test-guru pull request #24
Opened 2020-12-12 13:39 UTC by birzhans

2020-12-14 19:10 UTC, BubuntuClu requested changes

2020-12-14 19:10 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +      render :new
:edit

2020-12-14 19:10 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +      redirect_to admin_badges_path, alert: t('.failure')
почему редирект куда-то, а не отобразить форму для создания?

2020-12-14 19:10 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +      badges.each do |badge|
награждением пусть тоже сервис занимается, а не контроллер

2020-12-14 19:10 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    badges = BadgeService.new(@test_passage).call
вызывать сервис нет смысла, если тест не был пройден успешно

2020-12-14 19:10 UTC, BubuntuClu commented on app/models/badge.rb
> +    when "all_by_category"
при добавлении новых правил, эта лестница будет расширятся.
сделай тут почти как в сервисе, просто вызывай метод на основе правила. send(rule) и реализацию методов сделай тут

2020-12-14 19:10 UTC, BubuntuClu commented on app/services/badge_service.rb
> +                select(:id).map {|t| t.id}.
это все может сделать pluck

2020-12-14 19:10 UTC, BubuntuClu commented on app/services/badge_service.rb
> +                to_a.sort
сортировку делай через БД
запрос должен максимально подготовленные данные доставать

2020-12-14 19:10 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    tests = Test.where('category_id = ?', category.id)
через один запрос это сделай. вспоминай первые задания с join

2020-12-14 19:10 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def tests_ids(tests)
в запрос это помести, а не методами рубей гоняй массивы

2020-12-14 19:10 UTC, BubuntuClu commented on app/services/badge_service.rb
> +  def passed_tests
этот метод вообще нечитаемый

2020-12-14 19:10 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    if test_passages.count.eql?(1) && test_passages[0].passed
test_passages[0].passed это условие стоит вынести вообще до вызова сервиса

2020-12-14 19:10 UTC, BubuntuClu commented on app/services/badge_service.rb
> +      send("#{badge.rule}")
передавай бейдж в метод явно `send("#{badge.rule}", badge)`

2020-12-15 07:07 UTC, BubuntuClu requested changes

2020-12-15 07:07 UTC, BubuntuClu commented on app/models/badge.rb
> +  def check_all_by_category(test_passage)
не, это должно остаться в сервисе. это не обязанность модели

2020-12-15 07:07 UTC, BubuntuClu commented on app/services/badge_service.rb
> -  def all_tests
это все тут останется.

2020-12-15 07:07 UTC, BubuntuClu commented on app/models/badge.rb
> +    tests_by_category = Test.where(category_id: category_id)
нет, вспоминай join. ты все равно тут делаешь два запроса на то чтобы найти тесты. сначала ищешь категорию, потом тесты. сделай это через 1 запрос

2020-12-15 10:04 UTC, BubuntuClu approved these changes

2020-12-15 10:04 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def get_badges
рудимент какой-то, он нигде не используется

2020-12-15 10:04 UTC, BubuntuClu commented on app/models/user.rb
> +  def completed_tests
почему через метод, а не через скоуп?

2020-12-15 10:04 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    user_level_tests = test_passage.user.completed_tests.where('level = ?', level)
если в уровне 2 теста. ты прошел первый тест успешно. и решил еще раз его пройти. проходишь его еще раз успешно. ты должен получить бейдж за прохождение всех тестов уровня? нет, так как остался еще один тест, который ты не проходил. а по твоему условию ты получишь бейдж? да, получишь. нужно уникальные значения проверять

2020-12-15 10:04 UTC, BubuntuClu commented on app/services/badge_service.rb
> +    user_tests_by_category = test_passage.user.completed_tests.joins(:categories).where("categories.id = ?",  test_passage.test.category.id)
здесь тоже самое что и в проверке уровня

2020-12-15 10:04 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    if @test_passage.passed
давай избавимся от вложенного ифа.
выходи из метода, если тест неуспешный.
`return if...`

2020-12-15 12:42 UTC, birzhans commented on app/controllers/test_passages_controller.rb
> +    if @test_passage.passed
еще можно вызвать хелпер для флэш сообщений

2020-12-15 15:38 UTC, merged